/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "surface-bright": "#fff8f0",
        "tertiary": "#47331e",
        "primary-fixed": "#ffdad3",
        "on-secondary-fixed": "#062107",
        "tertiary-fixed": "#fedcbe",
        "on-primary-fixed-variant": "#812818",
        "secondary-container": "#c8e9bf",
        "surface-container-highest": "#ede2c8",
        "surface-container": "#f8edd3",
        "surface-container-low": "#fef3d9",
        "on-error-container": "#93000a",
        "secondary-fixed-dim": "#afcfa7",
        "on-surface": "#201b0c",
        "on-secondary-fixed-variant": "#324d2f",
        "error-container": "#ffdad6",
        "tertiary-fixed-dim": "#e1c1a4",
        "inverse-primary": "#ffb4a6",
        "on-background": "#201b0c",
        "inverse-on-surface": "#fbf0d6",
        "on-primary-container": "#ffa898",
        "on-secondary-container": "#4d6a48",
        "on-tertiary-fixed-variant": "#59422c",
        "inverse-surface": "#36301f",
        "on-secondary": "#ffffff",
        "on-primary-fixed": "#3f0300",
        "surface-container-lowest": "#ffffff",
        "surface": "#fff8f0",
        "on-tertiary": "#ffffff",
        "on-error": "#ffffff",
        "error": "#ba1a1a",
        "on-surface-variant": "#56423e",
        "tertiary-container": "#604933",
        "surface-variant": "#ede2c8",
        "outline-variant": "#ddc0bb",
        "primary-fixed-dim": "#ffb4a6",
        "secondary-fixed": "#cbecc2",
        "background": "#fff8f0",
        "primary": "#6b170a",
        "surface-dim": "#e4d9c0",
        "primary-container": "#8a2e1e",
        "on-primary": "#ffffff",
        "surface-tint": "#a13f2d",
        "on-tertiary-container": "#d9b99c",
        "secondary": "#496645",
        "surface-container-high": "#f3e7ce",
        "outline": "#8a726d",
        "on-tertiary-fixed": "#291806"
      },
      "borderRadius": {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      "spacing": {
        "gutter": "24px",
        "unit": "8px",
        "margin-desktop": "64px",
        "container-max-width": "1200px",
        "margin-mobile": "16px"
      },
      "fontFamily": {
        "body-lg": ["Montserrat", "sans-serif"],
        "title-lg": ["Montserrat", "sans-serif"],
        "headline-lg-mobile": ["\"Source Serif 4\"", "serif"],
        "headline-md": ["\"Source Serif 4\"", "serif"],
        "body-md": ["Montserrat", "sans-serif"],
        "display-lg": ["\"Source Serif 4\"", "serif"],
        "headline-lg": ["\"Source Serif 4\"", "serif"],
        "label-md": ["Montserrat", "sans-serif"]
      },
      "fontSize": {
        "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
        "title-lg": ["20px", {"lineHeight": "28px", "letterSpacing": "0.05em", "fontWeight": "600"}],
        "headline-lg-mobile": ["28px", {"lineHeight": "36px", "fontWeight": "600"}],
        "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "500"}],
        "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "display-lg": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "600"}],
        "headline-lg": ["32px", {"lineHeight": "40px", "fontWeight": "600"}],
        "label-md": ["14px", {"lineHeight": "20px", "letterSpacing": "0.1em", "fontWeight": "600"}]
      }
    },
  },
  plugins: [],
};
